TUGAS1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_1.urls as app_1
import app_2.urls as app_2
import app_3.urls as app_3
import app_4.urls as app_4
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url="/app-1/", permanent = "true"), name='index'),
    url(r'^app-1/', include(app_1 , namespace='app-1')),
    url(r'^app-2/', include(app_2 , namespace='app-2')),
    url(r'^app-3/', include(app_3,namespace='app-3')),
    url(r'^app-4/', include(app_4,namespace='app-4')),
]

app_1/urls.py
from django.conf.urls import url
from .views import index, add_status
from . import views

urlpatterns = [
	url(r'^$', index, name='index'),
	
	url(r'^add_status', add_status, name='add_status'),
	
	 
]

app_2/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_3/urls.py
from django.conf.urls import url
from .views import index, add_friend
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'add_friend', add_friend, name='add_friend'),
    ]

app_4/urls.py
from django.conf.urls import url
from .views import index
urlpatterns = [
    url(r'^$', index, name='index'),
    ]

app_1/models.py
from django.db import models

class Status(models.Model):
	description = models.CharField(max_length=140)
	created_date = models.DateTimeField(auto_now_add=True)

app_2/models.py
from django.db import models

# Create your models here.
class Data(models.Model):
	name = models.CharField(max_length=25)
	birthday = models.CharField(max_length=20)
	gender = models.CharField(max_length=6)
	expertise = models.TextField()
	description = models.TextField()
	email = models.EmailField()
	imageurl = models.TextField()
	
	def __str__(self):
		return self.name

app_3/models.py
from django.db import models

class Friend(models.Model):
    name = models.CharField(max_length=27)
    url = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

app_4/models.py
from django.db import models

# Create your models here.

app_1/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
   
    
    description_attrs = {
        'type': 'text',
				
        'class': 'status-form-textarea',
        'placeholder':'Apa yang anda pikirkan?...'
    }

    
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))
	

app_3/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    name_attrs = {
        'type': 'text',
        'class': 'name-form',
        'placeholder': 'Masukan nama...',
    }
    url_attrs = {
        'type': 'text',
        'class': 'url-form',
        'pattern': '^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$',
        'placeholder': 'Masukan url... (ex: http://debug-blaster.herokuapp.com)',
    }

    name = forms.CharField(label='Nama', max_length=27, required=True, widget=forms.TextInput(attrs=name_attrs))
    url = forms.CharField(widget=forms.TextInput(attrs=url_attrs), max_length=27, required=True)

app_1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from app_3.models import Friend
from app_2.models import Data

from .forms import Status_Form
from .models import Status

# Create your views here.

response = {}
def index(request):
	
    response['author'] = "Rafif Iqbal Shaputra" #TODO Implement yourname
    status= Status.objects.all()
    list_friend=Friend.objects.all()
    data=Data.objects.all()
    count_status=Status.objects.all().count()
    friend= Friend.objects.all().count()
    response['friend']=friend
    response['data']=data
    response['status'] = status[::-1]
    response['list_friend']= list_friend[0:4]
    response['count_status']=count_status
	
    html = 'app_1/app_1.html'
    response['status_form'] = Status_Form
	
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        return HttpResponseRedirect('/app-1/')
    else:
        return HttpResponseRedirect('/app-1/')
		

app_2/views.py
from django.shortcuts import render
from .models import Data

# Create your views here.
response = {}

def index(request):
	data = Data.objects.all()[0]
	response['data'] = data
	
	expertise = data.expertise
	expertiseSplit = expertise.split(",")
	response['expertise'] = expertiseSplit
	
	html = 'app_2/app_2.html'
	return render(request, html, response)

app_3/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

response = {'author' : "Kelompok 3A"}

def index(request):
    response['content'] = 'sesuatu'
    html = 'app_3/app_3.html'
    friend = Friend.objects.all()
    friend = reversed(friend)
    response['friend'] = friend
    response['friend_form'] = Friend_Form
    print(response['friend_form'])
    return render(request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friend = Friend(name=response['name'], url=response['url'])
        friend.save()
        return HttpResponseRedirect('/app-3/')
    else:
        print("tidak valid")
        return HttpResponseRedirect('/app-3/')

app_4/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from app_1.models import Status
from app_3.models import Friend

response = {}
def index(request):
    author = 'Rafif Iqbal Shaputra'
    response['author'] = author

    friends = len(Friend.objects.all())
    response['friends'] = friends

    feeds = len(Status.objects.all())
    response['feeds'] = feeds

    last = Status.objects.last()
    response['last'] = last


    html = 'app_4.html'
    return render(request, html, response)

app_1/templates/app_1/app_1.html

{% load staticfiles %}
{% load static %}

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/app_1.css' %}" />
</head>

{% block content %}
<div class="navbar">
	<a class="nav-link" href="/app-4/">Stat</a>
	<a class="nav-link" href="/app-3/">Friends</a>
	<a class="nav-link" href="/app-2/">Profile</a>
	<a class="nav-link" href="/app-1/">Status</a>
</div>


<div class="left-content">
	<section name="list-profile" id="list-profile">
		<img src="http://www.mediafire.com/convkey/db67/bmkz78dok9w1ww6zg.jpg" id="img-left"  />
		<p id="tulisan7">
			<b> Rafif Iqbal Shaputra</b>
		</p>

		<p id="tulisan8">
		<b><img src="https://cdn3.iconfinder.com/data/icons/line-icons-medium-version/64/comment-512.png" class="icon_post"/> {{count_status}}<br><br>
		<img src="https://cdn4.iconfinder.com/data/icons/eldorado-user/40/friends-512.png" class="icon_post"/>  {{friend}} <b><br>
		</p>
		<p id="data-profile">
		
		{% if data %}

					{% for i in data %}
						{{i.expertise}}<br>
						
						{{i.email}}<br>
						
						{{i.birthday}}<br>
						{{i.gender}}<br>
					{% endfor %}



				{% else %}

					
				{% endif %}
		
		</p>

	</section>
	<br>



</div>

<div class="right-content">

	<section id="belakang">
		<img src="http://www.mediafire.com/convkey/db67/bmkz78dok9w1ww6zg.jpg" class="img"  />
		<p class="tulisan4 	">
			<b> Rafif Iqbal Shaputra</b>
		</p>

		<p class="tulisan5">
		<b><img src="https://cdn3.iconfinder.com/data/icons/line-icons-medium-version/64/comment-512.png" class="icon_post"\>{{count_status}}<br><br>
		<img src="https://cdn4.iconfinder.com/data/icons/eldorado-user/40/friends-512.png" class="icon_post"/>  {{friend}} <b>

		</p>

		<section name="input-list" id="input-list">
			<div class="container_1">
				<div style=”text-align:justify;width:75%; background-color:#ff9999; border:1px solid #000099; padding:8px;”>

					<p class="nama" > <b> Whats Happening?</p> </b></div>
					<form id="form" method="POST" action="{% url 'app-1:add_status' %}">
						{% csrf_token %}
						{{ status_form }}
					<input id="submit" type="submit" class="post-button" value="Post">

					</form>

				</div>
		</section>

	</section>

	<section id="belakang_2">
		


		<section name="my-list" id="my-list">
			<section name="tulisan" id="tulisan">
				<p class="tulisan-tulis">
					<b>See All Status</b>
				</p>
			</section>
			<div class="container_2">

				<div class="flex">

				{% if status %}

					{% for data in status %}
					<div class="flex-item">
						<p id="prof" >
							<img src="http://www.mediafire.com/convkey/db67/bmkz78dok9w1ww6zg.jpg" class="img-flex"  />
							<br>Rafif Iqbal Shaputra<br>{{data.created_date}} <hr>
						</p>

						<p id="desc">
							{{data.description}}
						</p>
					 </div>
					 <br>
					{% endfor %}



				{% else %}

					<div class="alert alert-danger text-center">
						<strong>Oops!</strong> Tidak ada data status.
					</div>
				{% endif %}
				</div>

			</div>
		</section>
	</section>

</div>

<div class="right2-content">
	
	

	<section name="list-friend" id="list-friend">
	<p id="tulis">My Friend</p>
	<hr>
	<br>
	<div id=list_nama>
	{% if list_friend %}
		{% for data in list_friend %}

			<tr>
			<li>{{data.name}}<br></li>
			{{data.url}}<br><br>
			</tr>

		{% endfor %}

	{%endif%}

	</div>
	</section>

</div>




<footer>
	<p class="footer">&copy; made with love by KELOMPOK 3</p>
</footer>

{% endblock %}

app_1/templates/app_1/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 5">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/app_1.css' %}" />

    <title>
        {% block title %} Lab 5 By {{author}} {% endblock %}
    </title>
</head>

<body>
    <header>

    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
      
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

app_2/templates/app_2/app_2.html
{% extends "app_2/layout/base.html" %}
{% block content %}
<h1 class="tittle">Profile</h1>
<hr/>
<div class="navbar">
	<a class="nav-link" href="/app-4/">Stat</a>
	<a class="nav-link" href="/app-3/">Friends</a>
	<a class="nav-link" href="/app-2/">Profile</a>
	<a class="nav-link" href="/app-1/">Status</a>
</div>

<section name="bio">
	<center>
		<div class="container">
			<center>
				<img class="img-circle" src={{data.imageurl}} width="250" height="250">
			</center>
			<h3 align="center"> {{data.name}} </h3>
			<table align="center" style="text-align: justify">
				<tr>
					<td> Birthday </td>
					<td> {{data.birthday}} </td>
				</tr>
				<tr>
					<td> Gender </td>
					<td> {{data.gender}} </td>
				</tr>
				<tr>
					<td> Expertise </td>
					<td>
						<ul class="allTags">
							{% for exp in expertise %}
								<li>
									<a class="tag">{{exp}}</a>
								</li>
							{% endfor %}
						</ul>
					</td>
				</tr>
				<tr>
					<td> Description </td>
					<td> {{data.description}} </td>
				</tr>
				<tr>
					<td> Email </td>
					<td> {{data.email}} </td>
				</tr>
		</div>
	</center>
</section>

<footer>
	<p class="footer">&copy; made with love by KELOMPOK 3</p>
</footer>
{% endblock %}

app_2/templates/app_2/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		{% block title %} Profile {% endblock %}
    </title>
</style>
<style>
	h1, h3, td {
		font-family: "Calibri";
	}
	h1 a {
		color: #000000;
		text-decoration: none;
	}
	hr {
		border: 1px transparent;
	}
	td {
		vertical-align: top;
		max-width: 70%;
		word-wrap: break-word;
		padding-left: 20px;
		padding-right: 20px;
		padding-bottom: 8px;
	}

	body {
	  background-color: #E6E6FA;
	  font-family: Poppins;
	  color: gray;
		margin-top: 100px;
	  letter-spacing: 2.002px;
	  margin-bottom: 150px;
	}


	.navbar {
	  overflow: hidden;
	  background-color: #E6E6FA;
	  position: fixed;
	  top: 0;
	  width: 100%;

	}

	.navbar a {
	  font-family: Poppins;
	  font-size: 14px;
	  color: gray;
	  text-transform: uppercase;
	  letter-spacing: 2.002px;
	  padding-top: 25px;
	  padding-right: 83px;
	  text-decoration: none;
	  float: right;
	  display: block;


	}

	.navbar a:hover {
	  color: white;
	}

	.footer {
	  background-color: #E6E6FA;
	  position: fixed;
	  bottom: -2%;
	  width: 100%;
	  height: 3rem;
	  margin-top: 5rem;
	  padding-top: 20px;
	  text-align: center;
	  font-size: 14px;
	  text-transform: none;
	  font-weight: lighter;
		transform: translateX(-26.5%);
	}

	.allTags {
		list-style: none;
		margin: 0;
		overflow: hidden;
		padding: 0;
	}
	.tags li {
		float: left;
	}
	.tag {
		background: #eeeeee;
		border-radius: 10px;
		display: inline-block;
		height: 26px;
		line-height: 26px;
		padding: 0 20px 0 23px;
		position: relative;
		margin: 0 10px 5px 0;
		text-decoration: none;
		-webkit-transition: color 0.2s;
	}
	.tag:hover {
		background-color: #3a5fff;
		color: white;
	}
	.tag:hover::after {
		border-left-color: #3a5fff;
	}
	.img-circle {
		border-radius : 50%;
	}
	.container {
		border-radius: 45px;
		padding-top: 30px;
		padding-bottom: 30px;
		height: auto;
		width: 80%;
		background: #fff;
	}

	.tittle {
		text-align: center;
	}

</style>
<body style="background-color: #E6E6FA">
	{% block content %}
		<!-- content goes here -->
	{% endblock %}
</body>
</html>

app_3/templates/app_3/app_3.html
{% extends "app_3/layout/base.html" %}

{% block content %}
    <div class= "contain">
      <form class= "friend-form" method="POST" action="{% url 'app-3:add_friend' %}">
        <h2>Add Friend</h2>
        {% csrf_token %}
        {{ friend_form }}
        <button  class="friend-button">Add friend</button>
      </form>
    </div>
    <div class= "contain">
      <h2>Friend List</h2>
      <div class= "flex">
        {% if friend %}
          {% for data in friend %}
            <div class= "flex-item">
              <div class= "friend">
                <div class= "friend-name">
                  {{ data.name }}
                </div>
                <a class= "friend-url" target="_new" href="{{ data.url }}">
                  {{ data.url }}
                </a>
                <div class= "friend-added-date">
                  {{ data.created_date }}
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
        {% endif %}
      </div>
    </div>
  {% endblock %}

app_3/templates/app_3/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="App 3">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <title>
        {% block title %} Friends of {{author}}{% endblock %}
    </title>
</head>
<style>
body {
  background-color: #E6E6FA;
  font-family: Poppins;
  font-size: 14px;
  color: gray;
  text-transform: uppercase;
  letter-spacing: 2.002px;
  margin-bottom: 150px;
}

 

.navbar {
  overflow: hidden;
  background-color: #E6E6FA;
  position: fixed;
  top: 0;
  width: 100%;

}

.navbar a {
  font-family: Poppins;
  font-size: 14px;
  color: gray;
  text-transform: uppercase;
  letter-spacing: 2.002px;
  padding-top: 25px;
  padding-right: 83px;
  text-decoration: none;
  float: right;
  display: block;
  align-content: center;

}

.navbar a:hover {
  color: white;
}

.footer {
  background-color: #E6E6FA;
  letter-spacing: 2.002px;
  position: fixed;
  bottom: 20px;
  width: 100%;
  height: 3rem;
  margin-top: 5rem;
  padding-top: 20px;
  text-align: center;
  font-size: 14px;
  text-transform: none;
  font-weight: lighter;
}

    .contain {
        margin-left: 15%;
        margin-right: 15%;
        padding-left: 2%;
        padding-right: 2%;
        background-color: #E6E6FA;
    }

    h2 {
        font-family: arial;
        text-align: center;
        margin-top: 8px;
        padding-top: 15px;
    }

    .friend-form {
        display: flex;
        flex-flow: column wrap;
        width: 100%;
        margin-left: auto;
        margin-right: auto;
        margin-bottom: 0;
        margin-top: 100px;
        text-align: center;
        position: relative;
        background: white;
        border: 2px solid blueviolet;
        border-radius: 25px;
        padding: 20px;
        box-sizing: border-box;
    }

    .name-form {
        text-align: center;
        border-style: inset;
        padding: 8px 0;
        border-radius: 5px;
        width: 100%;
    }

    .url-form {
        text-align: center;
        margin-top: 15px;
        border-radius: 5px;
        border-style: inset;
        padding: 10px 0;
        font: 13.3333px Arial;
        width: 100%;
    }

    .friend-button {
        font: 13.3333px Arial;
        padding: 10px, 0;
        margin-top: 15px;
        border-radius: 5px;
        padding: 5px 0;
        background-color: #3b5998;
        color: white;
    }

    .flex {
        width: 100%;
        margin-left: auto;
        margin-right: auto;
        padding: 20px 30px;
        box-sizing: border-box;
    }

    .flex-item {
        display: flex;
        flex-direction: row;
        padding: 10px 5px;
        border-radius: 5px;
    }

    .flex-item:hover {
        box-shadow: 1px 1px 0 0 rgba(0, 0, 0, 0.4);
        transition: all ease 0.5s;
        background-color: rgba(0, 0, 0, 0.03);
    }

    .friend {
        width: 100%;
        font: 13.3333px Arial;
    }

    .friend-name {
        float: left;
        width: 30%;
    }

    .friend-url {
        text-align: right;
        float: right;
        width: 55%;
        overflow: hidden;
    }

    .friend-added-date {
        text-align: right;
        clear: both;
        font-size: 13px;
    }


    @media screen and (max-width: 768px) {
        .contain {
            margin-left: 0;
            margin-right: 0;
        }

        .flex-item {
            box-shadow: 1px 1px 0 0 rgba(0, 0, 0, 0.4);
            background-color: rgba(0, 0, 0, 0.03);
        }

        .friend {
            overflow: visible;
        }

        .friend-name {
            float: none;
            width: 100%
        }

        .friend-url {
            float: none;
            text-align: left;
            width: 100%;
            font-size: 11px;
        }

        .friend-added-date {
            float: none;
        }

        .friend-button {
            padding: 3% 0;
        }

    }
</style>
<body>
    <header>
      <div class="navbar">
        <a class="nav-link" href="/app-4/">Stat</a>
        <a class="nav-link" href="/app-3/">Friends</a>
        <a class="nav-link" href="/app-2/">Profile</a>
        <a class="nav-link" href="/app-1/">Status</a>
    </div>
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </div>

    </content>
    <footer>
        <p class="footer">&copy; made with love by KELOMPOK 3</p>
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js"></script> -->
</body>

 <!-- <script>
    $(function(){
      $('#form1').validate({
        rules: { //yang dicari name nya bukan id
          name:"required",
          age:{
            required: true,
            maxlength: 3
          }
        },
        messages:{
          name:"Jangan lupa diisi"
        },
        submitHandler: function(bebas){
          bebas.submit();
        }
      })
    })
</script>  -->
</html>

app_3/templates/app_3/partials/footer.html
<p style="margin: 10px;">&copy; {{author}}</p>

app_3/templates/app_3/table.html
{% extends "app_3/layout/base.html" %}

{% block title %} Friends {% endblock %}

{% block content %}
<!--  Populate semua isi pesan dari model -->
<p>Add Friend</p>
<table class="table">
    
    <tbody>
        <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
        {% for i in friend %}
        <tr class="success">
            <td> {{i.name}} </td>
            <td> {{i.url}} </td>
            <td> {{i.created_date}} </td>
        </tr>             
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app_4/templates/app_4.html
{% load static %}

<html lang="en">
  <head>
    <title>app_4 Statistic</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/app_4.css' %}"

  </head>

  <body>
    <div class="navbar">
      <a class="nav-link" href="/app-4/">Stat</a>
      <a class="nav-link" href="/app-3/">Friends</a>
      <a class="nav-link" href="/app-2/">Profile</a>
      <a class="nav-link" href="/app-1/">Status</a>
    </div>

    <div class="tittle">
      <h1>statistic</h1>
    </div>

    <div class="profile">
      <img src="http://www.mediafire.com/convkey/db67/bmkz78dok9w1ww6zg.jpg">
    </div>

    <div class="name">
      <h1>{{author}}</h1>
    </div>

    <div class="data">
      <h1>Friends</h1>
      <p>{{friends}} people</p>
      <h1>Feeds</h1>
      <p>{{feeds}} feeds</p>
      <h1>last status</h1>
    </div>

    <div class= "mini_profile">
        <h1>{{author}}<h1>
        <p class="status">{{last.description}}</p>
        <p>{{last.created_date}}</p>
    </div>

    <footer>
      <p class="footer">&copy; made with love by KELOMPOK 3</p>
    </footer>

  </body>

</html>